version: '3'
services:
  pysyncobj:
    build: .
    environment:
      - port=45892
      - APPLICATION_PORT=458
    deploy:
      replicas: 3
    networks:
      - net

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - pysyncobj
      ports:
        - "4000:4000"
      networks:
        - net

networks:
  net:
    driver: bridge